### ISSUE TITLE
High amount of metrics

### ISSUE THREAD

**Issue by achawki** [cloudfoundry/grootfs#12]
Hi,

we are on cf-deployment v1.9.0, garden-runc v1.11.0. We see in our environment with 450 cells about 12k metrics per seconds only related to `origin:"grootfs"`.  For now this is not causing a problem for us, since we are just filtering out corresponding metrics.

The top `valueMetrics` in our environment within about 30s:

```
   5093 origin:"grootfs"valueMetric:<name:"memoryStats.lastGCPauseTimeNS"
   5142 origin:"grootfs"valueMetric:<name:"memoryStats.numBytesAllocatedStack"
   5150 origin:"grootfs"valueMetric:<name:"memoryStats.numBytesAllocated"
   5160 origin:"grootfs"valueMetric:<name:"numCPUS"
   5170 origin:"grootfs"valueMetric:<name:"memoryStats.numFrees"
   5170 origin:"grootfs"valueMetric:<name:"memoryStats.numMallocs"
   5187 origin:"grootfs"valueMetric:<name:"memoryStats.numBytesAllocatedHeap"
   5203 origin:"grootfs"valueMetric:<name:"ImageStatsTime"
   5223 origin:"grootfs"valueMetric:<name:"numGoRoutines"
```
These metrics are coming per cell, in cases even multiple times per second.  

The top `counterEvents` in our enviroment within about 30s:
```
    ...[others not related to `grootfs`]
   4523 origin:"grootfs"counterEvent:<name:"grootfs-stats.run"
   4557 origin:"grootfs"counterEvent:<name:"grootfs-stats.run.success"
```

Wouldn't the `"grootfs-stats.run"` entries be more suitable for a debug log message instead of a metric?

**Comment by teddyking** [comment]
Hey @achawki, this got fixed a few weeks ago so I'm going to close this.

Thanks!
Ed
