### ISSUE TITLE
Feature Request: Support for "Content trust" for docker images

### ISSUE THREAD

**Issue by keymon** [cloudfoundry/grootfs#16]
What?
------

Docker supports a feature called "Content trust" : https://docs.docker.com/engine/security/trust/content_trust/ where the docker images are verified against a signature when they are downloaded from the registry. 

Some tenants are requesting us this feature, asking to enable this check per application. 

Grootfs can validate the image as it gets downloaded. The challenge is how the user can enable this feature and how the rest of the cloudfoundry stack should handle the situation.

Maybe a custom parameter in the docker url? e.g. `docker://myregistry/image?content_trust=true`

**Comment by julz** [comment]
Hi @keymon - sorry for the slow reply on this, the tldr is we're unlikely to do this feature on top of groot but we're planning to move over to containerd snapshot drivers _relatively_ soon (moving the stuff in groot we need upstream) which should give us a good amount of this "for free". I'd personally recommend people concerned with this not use image tags and instead use image content hashes which:
1. are stable and cryptographically un-swappable so have a lot of the features of Content Trust -- actually docker will use a content hash even with trust enabled without needing it to be signed ([trust only applies to tags](https://docs.docker.com/engine/security/trust/content_trust/#image-tags-and-dct)).
1. interact better with the CF push model where the expectation is there'll be a new 'push' if an image changes, avoiding you ending up with different containers having different versions of the image
