### ISSUE TITLE
No timeout when downloading Docker image Layers

### ISSUE THREAD

**Issue by vlast3k** [cloudfoundry/grootfs#182]
Recently during diego cell update, we noticed an issue where GrootFS was trying to download Docker Image Layers, but this took 30 and 70 minutes (for two instances of the app). As a result the call failed and this exception was written in the logs
```
 failed to create container: running image plugin create: pulling the image: streaming blob `sha256:7d92222c2b4c8e11483aa2b207d03f61c86433db5076c29e53e890e9e2152ddc`: writing blob to tempfile: read tcp 10.0.201.16:51246->104.18.124.25:443: read: connection reset by peer : exit status 1, reason: CRASHED
```
The same application instances later started and downloaded their blobs within few seconds. All in all docker blob downloads take up to 60s on our busiest landscapes, where up to 7000 LRPs (some of them docker) are updated at the same time.

For the customer this was recoded as downtime, as the new instances of the app did not manage to start on time, and the old one was killed after the rep evacuation timeout.

Tracing the issue in the code led to this part
https://github.com/cloudfoundry/grootfs/blob/5d15287e662a8d04d793d70bd681b5bd1d607da5/fetcher/layer_fetcher/source/layer_source.go#L209-L210

```
	for i := 0; i < MAX_DOCKER_RETRIES; i++ {
		logger.Debug(fmt.Sprintf("attempt-get-blob-%d", i+1))
		blob, size, e := imgSrc.GetBlob(context.TODO(), blobInfo, none.NoCache)
		if e == nil {
			logger.Debug("attempt-get-blob-success")
			return blob, size, nil
		}
		err = e
		logger.Error("attempt-get-blob-failed", err)
	}
```

And Get Blob (https://github.com/cloudfoundry/diego-release/blob/c256419f9d0878c3bff515bdb0a80eb49281e8b9/src/code.cloudfoundry.org/vendor/github.com/containers/image/docker/docker_image_src.go#L224-L234)

```
func (s *dockerImageSource) GetBlob(ctx context.Context, info types.BlobInfo, cache types.BlobInfoCache) (io.ReadCloser, int64, error) {
	if len(info.URLs) != 0 {
		return s.getExternalBlob(ctx, info.URLs)
	}

	path := fmt.Sprintf(blobsPath, reference.Path(s.ref.ref), info.Digest.String())
	logrus.Debugf("Downloading %s", path)
	res, err := s.c.makeRequest(ctx, "GET", path, nil, nil, v2Auth, nil)
	if err != nil {
		return nil, 0, err
	}
```
So it looks like it is time to take a look on the `context.TODO()` part and add some configurable timeout
E.g. default is no timeout, and via some config property, one could set it to some value - e.g. 60s.
This way the retry logic would handle such requests and quickly download the blob

If you agree, we will be happy to provide a PR

Regards, Vladimir

**Comment by MarcPaquette** [comment]
Hi @vlast3k 

Great writeup!  I've made sure this story has been added for discussion during our next internal planning meeting. 

We'll take a look and see what can be done to address this issue.

Thanks again for this awesome writeup!
@MarcPaquette

**Comment by MarcPaquette** [comment]
Hi @vlast3k,

We discussed this issue internally and we would love a PR for this issue!

Thanks for all your work so far on this!
@MarcPaquette

**Comment by vlast3k** [comment]
Hi @MarcPaquette ,

Great, we will include it in our planning in the next sprints and move forward

Regards, Vladimir
