### ISSUE TITLE
failed to unpack: : waiting for the reexec command failed 

### ISSUE THREAD

**Issue by Bean900** [cloudfoundry/grootfs#71]
**Actual behavior**
I am currently migrating my Dockerfiles to be build with Kaniko (V16 and V19 have been tried). The following error occurs in several of my Dockerfiles when starting in Cloud Foundry with `cf push` (Dockerimage build with kaniko: `thebohne/kaniko:kaniko`):
```
15:22:15.270: [CELL.0] Cell 7412a641-2c74-4f99-9cc0-788f7c4536fd failed to create container for instance 640101cd-af6c-467a-4b4e-d704: running image plugin create: pulling the image: unpacking layer `sha256:33db33d935721dfdf882423ee0e4d68410850032bc4e45779f7d746816710787`: failed to unpack: : waiting for the reexec command failed: unpacking-failed: opening target whiteout directory: open test: no such file or directory
15:22:15.270: [CELL.0] : exit status 1
```
or in another image:

```
Cell b87239a8-1b05-4ace-93b3-8a29484886d5 failed to create container for instance d6e31d31-7947-4ca7-7eda-651b: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/var/vcap/data/garden/bin/init\\\" to rootfs \\\"/var/vcap/data/grootfs/store/unprivileged/images/d6e31d31-7947-4ca7-7eda-651b/rootfs\\\" at \\\"/var/vcap/data/grootfs/store/unprivileged/images/d6e31d31-7947-4ca7-7eda-651b/rootfs/tmp/garden-init\\\" caused \\\"open /var/vcap/data/grootfs/store/unprivileged/images/d6e31d31-7947-4ca7-7eda-651b/rootfs/tmp/garden-init: permission denied\\\"\"": unknown
```

**Expected behavior**
The expected behavior looks like this when building with Docker (`docker build .`) and starting with `cf push` (Dockerimage build with docker: `thebohne/kaniko:docker`):
```
15:49:29.176: [CELL.0] Cell f3551e37-379f-454a-81d3-389a4c6d12a1 successfully created container for instance 77902562-a6aa-4aaf-7659-d8b3
15:49:31.431: [APP/PROC/WEB.0] Exit status 143
```

**To Reproduce**
For you, I wrote a minimal Dockerfile:
```
FROM debian:stretch
RUN mkdir /test
RUN echo "TEST" > /test/testfile
RUN mv /test/testfile /usr/local/bin
```
The same error should occur with other base images as well. 
I am running the following commands in my Jenkinspipeline (there should be no difference when running on your local maschine):

1. `/kaniko/executor --destination=thebohne/kaniko:kaniko --context=${WORKSPACE} --dockerfile=src/main/docker/Dockerfile` or with `--cache=true`
2. `CF_DOCKER_PASSWORD=${DOCKER_PASSWORD} cf push ${NAME} --docker-image thebohne/kaniko:kaniko --docker-username ${USERNAME} -u process`

**Test Matrix**
Here a little matrix of what I tested:
|| Run with Docker | Run in Cloud Foundry|
|---|---|---|
|Build with Docker|:heavy_check_mark:|:heavy_check_mark:|  
|Build with Kaniko|:heavy_check_mark:|:x:|

**Else**
So I don't know where to post this issue (I hope I'm in the right repo :grin:) because there's a link between Kaniko and Cloud Foundry.
Here is the link to the same issue that was published in the Kaniko repo: https://github.com/GoogleContainerTools/kaniko/issues/1149

Thanks for you help :) if you need additional information please write a comment :)

**Comment by danail-branekov** [comment]
Hello @Bean900 

As per the bug you refered to, Kaniko does not seem to handle files removal the way Docker does (i.e. it does not place a whiteout marker file in the layer that deletes the file from the previous layer).

It seems that @tejal29 already suggested a [fix](https://github.com/GoogleContainerTools/kaniko/issues/1149#issuecomment-625525433). We are pretty confident that resolving that would make Kaniko images usable with CF.

Or do you think that GrootFS should support Kaniko images as of today? If yes, that sounds like a feature request, not sure whether we can commit on implementing it. However, feel free to file a pull request.

cc: @kieron-pivotal

**Comment by Bean900** [comment]
Thanks for the answer.
I think I'll wait until Kaniko is fixed. Otherwise I would switch to a different technology where docker files can be built without root rights.
